

const BIRKELAND_WALLET_TRANSACTION_STATUS = {
    "CREATED" : "CREATED",
    "PENDING" : "PENDING",
    "SUCCESS" : "SUCCESS",
    "FAILED" : "FAILED"
}

module.exports = {BIRKELAND_WALLET_TRANSACTION_STATUS}